import type { CaptionStyle, CaptionTemplateId } from "@caption-generator/types";

export const CAPTION_TEMPLATES: Record<CaptionTemplateId, CaptionStyle> = {
  viral: {
    templateId: "viral",
    fontFamily: "Arial Black, Arial, sans-serif",
    fontSize: 72,
    fontWeight: 900,
    textColor: "#ffffff",
    activeColor: "#ffe600",
    strokeColor: "#101014",
    strokeWidth: 8,
    backgroundColor: "#000000",
    backgroundOpacity: 0,
    borderRadius: 18,
    maxWords: 4,
    uppercase: true,
    positionY: 72,
  },
  clean: {
    templateId: "clean",
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: 62,
    fontWeight: 750,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 2,
    backgroundColor: "#111116",
    backgroundOpacity: 0.78,
    borderRadius: 20,
    maxWords: 6,
    uppercase: false,
    positionY: 76,
  },
  neon: {
    templateId: "neon",
    fontFamily: "Arial Black, Arial, sans-serif",
    fontSize: 68,
    fontWeight: 900,
    textColor: "#f7f7ff",
    activeColor: "#95ff38",
    strokeColor: "#1b280d",
    strokeWidth: 5,
    backgroundColor: "#050505",
    backgroundOpacity: 0.22,
    borderRadius: 28,
    maxWords: 5,
    uppercase: true,
    positionY: 70,
  },
  boxed: {
    templateId: "boxed",
    fontFamily: "Arial, sans-serif",
    fontSize: 62,
    fontWeight: 850,
    textColor: "#141414",
    activeColor: "#ffffff",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#ffffff",
    backgroundOpacity: 0.96,
    borderRadius: 12,
    maxWords: 5,
    uppercase: false,
    positionY: 74,
  },
  karaoke: {
    templateId: "karaoke",
    fontFamily: "Georgia, serif",
    fontSize: 66,
    fontWeight: 800,
    textColor: "#ffffff",
    activeColor: "#ff5d8f",
    strokeColor: "#240713",
    strokeWidth: 5,
    backgroundColor: "#000000",
    backgroundOpacity: 0,
    borderRadius: 24,
    maxWords: 7,
    uppercase: false,
    positionY: 68,
  },
};

export const DEFAULT_CAPTION_STYLE = CAPTION_TEMPLATES.viral;
